# config.yaml
executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - Log In Flow
        - Search and Follow Profile Flow
        - Explore Follow Profile Flow
        - Log Out Flow
